### ISSUE TITLE
DocxTemplater doesn't work in IE 11

### ISSUE THREAD

**Issue by jehanzebafridi** [open-xml-templating/docxtemplater-build#3]
Hi,

Please can someone help. DocxTemplater works in Firefox and Chrome fine, but it does't work in IE 11. I have also tested the online demo at https://docxtemplater.com/demo/ in IE 11 and it doesn't work. Can someone please help?

Many thanks!

**Comment by edi9999** [comment]
1. For docxtemplater itself : 

That is strange. I have automated tests that are running in IE 11 : https://saucelabs.com/beta/tests/36ed33c6735e41e7aa48efcb1b7ff68d/commands#6

Do you have a stack trace that shows what is happening ? Usually, with IE, the problem is to load the document, which can be achieved easily : http://docxtemplater.readthedocs.io/en/latest/faq.html#support-for-ie9-and-lower

docxtemplater should be able to run on IE 8,9 and 10 

2. For the docxtemplater.com/demo page : that is right, I'm going to fix this, this is my mistake and doesn't have anything to do with the docxtemplater code itself

**Comment by edi9999** [comment]
I have moved this discussion to where it belongs , in the main docxtemplater repository : https://github.com/open-xml-templating/docxtemplater/issues/375
